### ISSUE TITLE
Task launched multiple times

### ISSUE THREAD

**Issue by LostArkTR** [eibex/reaction-light#82] opened 2021-06-30 10:31 UTC
**Describe the bug**

randomly getting this error but bot still working, i guess just one time bot stopped working when i get this error.

**Screenshots**

![image](https://user-images.githubusercontent.com/85989561/123945593-00232080-d9a7-11eb-90fc-ed249ebbfd2f.png)

**Server:**

- OS: Windows Server 2012
- Python version: 3.9
- discord.py version: 1.6 - 1.7

**Comment by Edwinexd** [comment] 2021-06-30 10:41
Hey! This is caused by the on_ready event being dispatched more than once which it does after a disconnect from discord, usually a result of an unstable internet connection, the error itself isn't causing any issue besides the traceback. This is getting fixed in the cogs rework where tasks will be guaranteed to be launched just once.

**Closed** 2021-11-30 17:07 UTC
Labels: bug
